version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: workpulse-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: workpulse
      POSTGRES_PASSWORD: workpulse
      POSTGRES_DB: workpulse
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: